"""Backend for the setup wizard (the pywebview UI's guided first-run flow): write config.toml from the
wizard's fields, test the GP connection read-only, and start/stop the serve process. These are the
non-display half of the wizard; the Api in ui.py wraps them for JS, and enrollment reuses
enroll.enroll_relay. Kept out of ui.py so it imports without the GUI backend (and unit-tests cleanly).

Config is generated from a template here rather than via get_settings so the wizard's write-then-test
step never fights get_settings's lru_cache, and so a not-yet-complete config (no real secret) can still
be written and probed.
"""

import json
import subprocess
import tomllib
from pathlib import Path

_PLACEHOLDER_SECRET = "REPLACE_ME_RANDOM_TOKEN"
_DEFAULT_DRIVER = "ODBC Driver 17 for SQL Server"
_DEFAULT_CORS = [
    "https://frontend-production-34fc.up.railway.app",
    "http://localhost:5173",
    "http://localhost:8000",
]


def _s(value: str) -> str:
    """A TOML basic string. json.dumps yields valid TOML for our plain values (and escapes correctly)."""
    return json.dumps(value)


def _arr(items) -> str:
    """A TOML array of strings - identical syntax to a JSON array of strings."""
    return json.dumps(list(items))


def build_config_toml(fields: dict) -> str:
    """Render config.toml text from the wizard fields. Only server/driver, companies, buyer, and
    backend_url are operator-supplied; the rest carry the documented defaults."""
    sql_server = fields.get("sql_server") or ""
    sql_driver = fields.get("sql_driver") or _DEFAULT_DRIVER
    default_company = fields.get("default_company") or "TUBC"
    allowed = fields.get("allowed_companies") or ["TUBC", "TUCSH"]
    buyer_default = fields.get("buyer_default") or ""
    backend_url = fields.get("backend_url") or ""
    cors = fields.get("cors_origins") or _DEFAULT_CORS
    custom_db = fields.get("custom_db") or {}
    secret = fields.get("shared_secret") or _PLACEHOLDER_SECRET

    out = [
        "# Generated by the UC Nexus Relay setup wizard. config.toml is gitignored (it holds the secret).",
        "",
        "[server]",
        'host = "127.0.0.1"',
        "port = 7321",
        "",
        "[auth]",
        f"shared_secret = {_s(secret)}",
        "",
        "[cors]",
        f"allowed_origins = {_arr(cors)}",
        "",
        "[sql]",
        f"server = {_s(sql_server)}",
        f"driver = {_s(sql_driver)}",
        "trusted_connection = true",
        'encrypt = "yes"',
        "trust_server_certificate = true",
        "connection_timeout = 10",
        "command_timeout = 30",
        "",
        "[gp]",
        f"default_company = {_s(default_company)}",
        f"allowed_companies = {_arr(allowed)}",
    ]
    if custom_db:
        out += ["", "[gp.custom_db]"] + [f"{k} = {_s(v)}" for k, v in custom_db.items()]
    if buyer_default:
        out += ["", "[gp.buyers]", f"default = {_s(buyer_default)}"]
    out += [
        "",
        "[logging]",
        'level = "INFO"',
        'file = "relay.log"',
        "",
        "[channel]",
        f"backend_url = {_s(backend_url)}",
        "",
    ]
    return "\n".join(out)


def write_config(fields: dict, config_path: str | Path) -> dict:
    """Write config.toml from the wizard fields. Preserves an already-enrolled secret so re-running setup
    on an enrolled relay doesn't silently wipe enrollment (caller can pass shared_secret to override)."""
    config_path = Path(config_path)
    fields = dict(fields)
    if "shared_secret" not in fields and config_path.exists():
        try:
            with open(config_path, "rb") as f:
                existing = tomllib.load(f)
            sec = (existing.get("auth") or {}).get("shared_secret")
            if sec and sec != _PLACEHOLDER_SECRET:
                fields["shared_secret"] = sec
        except (OSError, tomllib.TOMLDecodeError):
            pass
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(build_config_toml(fields), encoding="utf-8")
    return {"ok": True, "path": str(config_path)}


def _conn_string(sql: dict, company: str) -> str:
    parts = [
        f"DRIVER={{{sql.get('driver') or _DEFAULT_DRIVER}}}",
        f"SERVER={sql.get('server')}",
        f"DATABASE={company}",
    ]
    if sql.get("trusted_connection", True):
        parts.append("Trusted_Connection=yes")
    parts.append(f"Encrypt={sql.get('encrypt', 'yes')}")
    if sql.get("trust_server_certificate", True):
        parts.append("TrustServerCertificate=yes")
    parts.append(f"Connection Timeout={sql.get('connection_timeout', 10)}")
    return ";".join(parts) + ";"


def test_gp_connection(config_path: str | Path) -> dict:
    """Read-only GP connectivity + identity probe against [gp].default_company, built straight from the
    config file (not get_settings) so it reflects a just-written config. No eConnect, no writes."""
    import pyodbc

    try:
        with open(config_path, "rb") as f:
            data = tomllib.load(f)
    except (OSError, tomllib.TOMLDecodeError) as e:
        return {"ok": False, "error": f"cannot read config: {e}"}
    sql = data.get("sql") or {}
    if not sql.get("server"):
        return {"ok": False, "error": "no [sql].server set"}
    company = (data.get("gp") or {}).get("default_company") or "TUBC"
    try:
        with pyodbc.connect(_conn_string(sql, company), autocommit=True) as conn:
            row = conn.cursor().execute(
                "SELECT SUSER_NAME() AS login, DB_NAME() AS db, IS_MEMBER('DYNGRP') AS dyngrp"
            ).fetchone()
        return {
            "ok": True,
            "company": company,
            "connected_as": row.login,
            "database": row.db,
            "is_member_dyngrp": bool(row.dyngrp),
        }
    except pyodbc.Error as e:
        return {"ok": False, "error": str(e)}


def pid_file(config_dir: str | Path) -> Path:
    return Path(config_dir) / "relay.pid"


def start_serve(exe_path: str | Path, config_dir: str | Path) -> dict:
    """Launch `<exe> serve` detached (no window) with cwd=config_dir, so it finds config.toml and writes
    relay.log + relay.pid there. Returns the launcher pid; the reliable pid for stop is the one the serve
    process writes to relay.pid."""
    detached = 0x00000008  # DETACHED_PROCESS
    no_window = 0x08000000  # CREATE_NO_WINDOW
    proc = subprocess.Popen(
        [str(exe_path), "serve"],
        cwd=str(config_dir),
        creationflags=detached | no_window,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    return {"ok": True, "pid": proc.pid}


def stop_serve(config_dir: str | Path) -> dict:
    """Stop the serve process the UI started, by the pid it wrote to relay.pid. Returns ok even if the
    pid is already gone (nothing to stop)."""
    pf = pid_file(config_dir)
    if not pf.exists():
        return {"ok": False, "error": "no relay.pid (the relay was not started here, or isn't running)"}
    try:
        pid = int(pf.read_text().strip())
    except (OSError, ValueError):
        return {"ok": False, "error": "unreadable relay.pid"}
    result = subprocess.run(["taskkill", "/PID", str(pid), "/F"], capture_output=True, text=True)  # noqa: S607
    if result.returncode == 0:
        return {"ok": True, "pid": pid}
    return {"ok": True, "pid": pid, "note": (result.stderr or result.stdout or "").strip()}
